app = "qageeks"

kill_signal = "SIGINT"
kill_timeout = 5

[build]

[deploy]
[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false # Keep running for production
  auto_start_machines = true
  min_machines_running = 1   # Keep at least one instance running
  processes = ["app"]
